name: newcoin
description: "Project about newcoin list"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/coin_img/dogscoin.jpg
    - assets/coin_img/catscoin.jpg
    - assets/coin_img/goatscoin.jpg
    - assets/icons/icon.png

